version: '3'

services:
  mongo-1:
    container_name: mongo-1
    image: mongo:${MONGO_VERSION}
    command: --config /etc/mongod.conf
    restart: always
    environment:
       - MONGO_ADMIN_PASSWORD
    volumes:
      - ${DATA_PATH}/mongo-1/:/data/db
      - ${DATA_PATH}/mongo-key/rs.key:/mongo-key/rs.key
      - ./config/${CLUSTER_TYPE}/mongod.conf:/etc/mongod.conf
      - ./config/${CLUSTER_TYPE}/initiate.sh:/initiate.sh
    ports:
      - "30017:27017"
  mongo-2:
    container_name: mongo-2
    image: mongo:${MONGO_VERSION}
    command: --config /etc/mongod.conf
    restart: always
    volumes:
      - ${DATA_PATH}/mongo-2/db:/data/db
      - ${DATA_PATH}/mongo-key/rs.key:/mongo-key/rs.key
      - ./config/${CLUSTER_TYPE}/mongod.conf:/etc/mongod.conf
    ports:
      - "31017:27017"
  mongo-3:
    container_name: mongo-3
    image: mongo:${MONGO_VERSION}
    command: --config /etc/mongod.conf
    restart: always
    volumes:
      - ${DATA_PATH}/mongo-3/db:/data/db
      - ${DATA_PATH}/mongo-key/rs.key:/mongo-key/rs.key
      - ./config/${CLUSTER_TYPE}/mongod.conf:/etc/mongod.conf
    ports:
      - "32017:27017"
  mongo-hidden:
    container_name: mongo-hidden
    image: mongo:${MONGO_VERSION}
    command: --config /etc/mongod.conf
    restart: always
    volumes:
      - ${DATA_PATH}/mongo-hidden/db:/data/db
      - ${DATA_PATH}/mongo-key/rs.key:/mongo-key/rs.key
      - ./config/${CLUSTER_TYPE}/mongod.conf:/etc/mongod.conf
    ports:
      - "33017:27017"
  # mongo-express:
  #   container_name: mongo-express
  #   image: mongo-express
  #   restart: always
  #   environment:
  #     - ME_CONFIG_MONGODB_ADMINUSERNAME=${ROOT_USERNAME}
  #     - ME_CONFIG_MONGODB_ADMINPASSWORD=$MONGO_INITDB_ROOT_PASSWORD
  #     - ME_CONFIG_MONGODB_SERVER=mongo-1,mongo-2,mongo-3,mongo-hidden
  #   ports:
  #     - 8081:8081
